       [VendorID]
      ,[LastName]
      ,[FirstName]
  FROM [AP].[dbo].[ContactUpdates]

       [AccountNo]
      ,[AccountDescription]
  FROM [AP].[dbo].[GLAccounts]

     [InvoiceID]
    ,[VendorID]
    ,[InvoiceNumber]
    ,[InvoiceDate]
    ,[InvoiceTotal]
    ,[PaymentTotal]
    ,[CreditTotal]
    ,[TermsID]
    ,[InvoiceDueDate]
    ,[PaymentDate]
FROM [AP].[dbo].[InvoiceArchive]

     [InvoiceID]
    ,[InvoiceSequence]
    ,[AccountNo]
    ,[InvoiceLineItemAmount]
    ,[InvoiceLineItemDescription]
FROM [AP].[dbo].[InvoiceLineItems]

       [InvoiceID]
      ,[VendorID]
      ,[InvoiceNumber]
      ,[InvoiceDate]
      ,[InvoiceTotal]
      ,[PaymentTotal]
      ,[CreditTotal]
      ,[TermsID]
      ,[InvoiceDueDate]
      ,[PaymentDate]
  FROM [AP].[dbo].[Invoices]

       [TermsID]
      ,[TermsDescription]
      ,[TermsDueDays]
  FROM [AP].[dbo].[Terms]

       [VendorID]
      ,[VendorName]
      ,[VendorAddress1]
      ,[VendorAddress2]
      ,[VendorCity]
      ,[VendorState]
      ,[VendorZipCode]
      ,[VendorPhone]
      ,[VendorContactLName]
      ,[VendorContactFName]
      ,[DefaultTermsID]
      ,[DefaultAccountNo]
  FROM [AP].[dbo].[Vendors]